/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author RAVI PANCHAL
 */
public class Deposit extends javax.swing.JFrame {

    /**
     * Creates new form Deposit
     */
    public Deposit() {
        initComponents();
        showAcc();
    }
    public void showAcc()
    {
        String acc = SignupPage.acc;
        txt_account.setText(acc);
    }
    //deposit or credit money here
    public void Deposit()
    {
        String type = "Cr.";
        String t_type = "Deposit";
        String acc = txt_account.getText();
        int amt = Integer.parseInt(txt_depositamt.getText());
        int new_bal;
        try
        {
            Connection con = Dbconnection.getConnection();
            String sql = "select * from bank2 where no=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,acc);
            
            ResultSet rs = pst.executeQuery();
            rs.next();
            int oldbal = rs.getInt(3);
            //set new bal
            new_bal = oldbal + amt;
            //update new bal
            String sql1 = "update bank2 set bal=? where no = ?";
            PreparedStatement pst1 = con.prepareStatement(sql1);
            pst1.setInt(1,new_bal);
            pst1.setString(2,acc);
            int updateRowCount = pst1.executeUpdate();
            if(updateRowCount>0)
            {
                String sql2 = "insert into bank_tran values(?,?,?,?,?)";
                PreparedStatement pst2 = con.prepareStatement(sql2);
                pst2.setString(1,acc);
                pst2.setString(2,acc);
                pst2.setInt(3,amt);
                pst2.setString(4,type);
                pst2.setString(5,t_type);
                
                int updateRowCount2 = pst2.executeUpdate();
                if(updateRowCount2>0)
                {
                    JOptionPane.showMessageDialog(this,"Deposited");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Fail to Deposit");
            }
            //JOptionPane.showMessageDialog(this,new_bal);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    public Boolean checkField()
    {
        String amt = txt_depositamt.getText();
        if(amt.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Please Enter Amount");
            return false;
        }
        else
        {
            return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_account = new app.bolivia.swing.JCTextField();
        txt_depositamt = new app.bolivia.swing.JCTextField();
        deposit = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/MyBankicon/Deposit.png"))); // NOI18N
        rSPanelImage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Account No");
        rSPanelImage1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 150, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Amount");
        rSPanelImage1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 150, 50));

        txt_account.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 102, 0)));
        txt_account.setEnabled(false);
        rSPanelImage1.add(txt_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 250, 50));

        txt_depositamt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 102, 0)));
        txt_depositamt.setPlaceholder("Enter Amount To Deposit");
        rSPanelImage1.add(txt_depositamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 250, 50));

        deposit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        deposit.setForeground(new java.awt.Color(255, 255, 255));
        deposit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deposit.setText("Deposit");
        deposit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depositMouseClicked(evt);
            }
        });
        rSPanelImage1.add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 180, 36));

        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("Back");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        rSPanelImage1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 38, 100, 30));

        getContentPane().add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 650));

        setSize(new java.awt.Dimension(600, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void depositMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depositMouseClicked
        // TODO add your handling code here:
        if(checkField())
        {
            Deposit();
        }    
    }//GEN-LAST:event_depositMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        HomePage h = new HomePage();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Deposit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel deposit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private rojerusan.RSPanelImage rSPanelImage1;
    private app.bolivia.swing.JCTextField txt_account;
    private app.bolivia.swing.JCTextField txt_depositamt;
    // End of variables declaration//GEN-END:variables
}
